### ISSUE TITLE
Xworm

### ISSUE THREAD

**Issue by ihearttriplebaka** [MiningTcup/Roblox-Multi-Instance#12]
why does it say 10/10 xworm??

**Comment by MiningTcup** [comment]
On what tester?

**Comment by MiningTcup** [comment]
I see that someone wrote that in the comments of the VirusTotal page, but that VirusTotal itself did not detect anything to do with xworm. Since that post is community-made, it may not be accurate. Please compile from source if you are scared about malware. If you complain any more, I will assume you're a scammer.
